# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_dataimport.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1228, 437)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.import_button = QtWidgets.QPushButton(Dialog)
        self.import_button.setObjectName("import_button")
        self.horizontalLayout_4.addWidget(self.import_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.fileExtention_label = QtWidgets.QLabel(Dialog)
        self.fileExtention_label.setObjectName("fileExtention_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fileExtention_label)
        self.fileExtention_edit = QtWidgets.QLineEdit(Dialog)
        self.fileExtention_edit.setEnabled(False)
        self.fileExtention_edit.setObjectName("fileExtention_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fileExtention_edit)
        self.dataFormat_label = QtWidgets.QLabel(Dialog)
        self.dataFormat_label.setObjectName("dataFormat_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dataFormat_label)
        self.dataFormat_edit = QtWidgets.QLineEdit(Dialog)
        self.dataFormat_edit.setEnabled(False)
        self.dataFormat_edit.setObjectName("dataFormat_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dataFormat_edit)
        self.sliceData_label = QtWidgets.QLabel(Dialog)
        self.sliceData_label.setObjectName("sliceData_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.sliceData_label)
        self.slice_check = QtWidgets.QCheckBox(Dialog)
        self.slice_check.setEnabled(False)
        self.slice_check.setText("")
        self.slice_check.setObjectName("slice_check")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.slice_check)
        self.sampleFrequency_label = QtWidgets.QLabel(Dialog)
        self.sampleFrequency_label.setObjectName("sampleFrequency_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.sampleFrequency_label)
        self.sampleFrequency_Spin = QtWidgets.QDoubleSpinBox(Dialog)
        self.sampleFrequency_Spin.setEnabled(False)
        self.sampleFrequency_Spin.setObjectName("sampleFrequency_Spin")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sampleFrequency_Spin)
        self.columTime_label = QtWidgets.QLabel(Dialog)
        self.columTime_label.setObjectName("columTime_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.columTime_label)
        self.columnTime_combo = QtWidgets.QComboBox(Dialog)
        self.columnTime_combo.setEnabled(False)
        self.columnTime_combo.setObjectName("columnTime_combo")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.columnTime_combo)
        self.columnAcc_label = QtWidgets.QLabel(Dialog)
        self.columnAcc_label.setObjectName("columnAcc_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.columnAcc_label)
        self.columnAcc_combo = QtWidgets.QComboBox(Dialog)
        self.columnAcc_combo.setEnabled(False)
        self.columnAcc_combo.setObjectName("columnAcc_combo")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.columnAcc_combo)
        self.unitTime_label = QtWidgets.QLabel(Dialog)
        self.unitTime_label.setObjectName("unitTime_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.unitTime_label)
        self.unitTime_combo = QtWidgets.QComboBox(Dialog)
        self.unitTime_combo.setEnabled(False)
        self.unitTime_combo.setObjectName("unitTime_combo")
        self.unitTime_combo.addItem("")
        self.unitTime_combo.addItem("")
        self.unitTime_combo.addItem("")
        self.unitTime_combo.addItem("")
        self.unitTime_combo.addItem("")
        self.unitTime_combo.addItem("")
        self.unitTime_combo.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.unitTime_combo)
        self.unitAcc_label = QtWidgets.QLabel(Dialog)
        self.unitAcc_label.setObjectName("unitAcc_label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.unitAcc_label)
        self.unitAcc_combo = QtWidgets.QComboBox(Dialog)
        self.unitAcc_combo.setEnabled(False)
        self.unitAcc_combo.setObjectName("unitAcc_combo")
        self.unitAcc_combo.addItem("")
        self.unitAcc_combo.addItem("")
        self.unitAcc_combo.addItem("")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.unitAcc_combo)
        self.verticalLayout.addLayout(self.formLayout)
        self.status_label = QtWidgets.QLabel(Dialog)
        self.status_label.setObjectName("status_label")
        self.verticalLayout.addWidget(self.status_label)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.OK_buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.OK_buttonBox.setEnabled(False)
        self.OK_buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.OK_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.OK_buttonBox.setObjectName("OK_buttonBox")
        self.horizontalLayout_6.addWidget(self.OK_buttonBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sample_label = QtWidgets.QLabel(Dialog)
        self.sample_label.setObjectName("sample_label")
        self.verticalLayout_3.addWidget(self.sample_label)
        self.header_edit = QtWidgets.QPlainTextEdit(Dialog)
        self.header_edit.setEnabled(False)
        self.header_edit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.header_edit.setObjectName("header_edit")
        self.verticalLayout_3.addWidget(self.header_edit)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.data_table = QtWidgets.QTableWidget(Dialog)
        self.data_table.setEnabled(False)
        self.data_table.setObjectName("data_table")
        self.data_table.setColumnCount(0)
        self.data_table.setRowCount(0)
        self.verticalLayout_3.addWidget(self.data_table)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.timeOfMeasurement_edit = QtWidgets.QLineEdit(Dialog)
        self.timeOfMeasurement_edit.setEnabled(True)
        self.timeOfMeasurement_edit.setAutoFillBackground(False)
        self.timeOfMeasurement_edit.setObjectName("timeOfMeasurement_edit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.timeOfMeasurement_edit)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.sampleFrequency_edit = QtWidgets.QLineEdit(Dialog)
        self.sampleFrequency_edit.setEnabled(True)
        self.sampleFrequency_edit.setObjectName("sampleFrequency_edit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sampleFrequency_edit)
        self.rms_edit = QtWidgets.QLineEdit(Dialog)
        self.rms_edit.setEnabled(True)
        self.rms_edit.setObjectName("rms_edit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rms_edit)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)

        self.retranslateUi(Dialog)
        self.OK_buttonBox.accepted.connect(Dialog.accept)
        self.OK_buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.import_button.setText(_translate("Dialog", "Import"))
        self.fileExtention_label.setText(_translate("Dialog", "File extension"))
        self.dataFormat_label.setText(_translate("Dialog", "Data format"))
        self.dataFormat_edit.setText(_translate("Dialog", "%f"))
        self.sliceData_label.setText(_translate("Dialog", "Slice data?"))
        self.sampleFrequency_label.setText(_translate("Dialog", "Sample frequency"))
        self.columTime_label.setText(_translate("Dialog", "Column with time data"))
        self.columnAcc_label.setText(_translate("Dialog", "Column with acceleration data"))
        self.unitTime_label.setText(_translate("Dialog", "Unit of time data"))
        self.unitTime_combo.setItemText(0, _translate("Dialog", "ChipTimeUS"))
        self.unitTime_combo.setItemText(1, _translate("Dialog", "ns"))
        self.unitTime_combo.setItemText(2, _translate("Dialog", "ms"))
        self.unitTime_combo.setItemText(3, _translate("Dialog", "s"))
        self.unitTime_combo.setItemText(4, _translate("Dialog", "min"))
        self.unitTime_combo.setItemText(5, _translate("Dialog", "h"))
        self.unitTime_combo.setItemText(6, _translate("Dialog", "custom"))
        self.unitAcc_label.setText(_translate("Dialog", "Unit of acceleration data"))
        self.unitAcc_combo.setItemText(0, _translate("Dialog", "g"))
        self.unitAcc_combo.setItemText(1, _translate("Dialog", "ms^2"))
        self.unitAcc_combo.setItemText(2, _translate("Dialog", "custom"))
        self.status_label.setText(_translate("Dialog", "Status: "))
        self.sample_label.setText(_translate("Dialog", "Header"))
        self.label_4.setText(_translate("Dialog", "Data"))
        self.label_2.setText(_translate("Dialog", "Sample Frequency (Hz)"))
        self.label.setText(_translate("Dialog", "Time of meassurement (min):"))
        self.label_3.setText(_translate("Dialog", "RMS (g)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

