# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_wavimport.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1228, 454)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.import_button = QtWidgets.QPushButton(Dialog)
        self.import_button.setObjectName("import_button")
        self.horizontalLayout_4.addWidget(self.import_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.columTime_label = QtWidgets.QLabel(Dialog)
        self.columTime_label.setObjectName("columTime_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.columTime_label)
        self.columnTime_combo = QtWidgets.QComboBox(Dialog)
        self.columnTime_combo.setEnabled(False)
        self.columnTime_combo.setObjectName("columnTime_combo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.columnTime_combo)
        self.columnAcc_label = QtWidgets.QLabel(Dialog)
        self.columnAcc_label.setObjectName("columnAcc_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.columnAcc_label)
        self.columnAcc_combo = QtWidgets.QComboBox(Dialog)
        self.columnAcc_combo.setEnabled(False)
        self.columnAcc_combo.setObjectName("columnAcc_combo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.columnAcc_combo)
        self.unitTime_label = QtWidgets.QLabel(Dialog)
        self.unitTime_label.setObjectName("unitTime_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.unitTime_label)
        self.unitTime_combo = QtWidgets.QComboBox(Dialog)
        self.unitTime_combo.setObjectName("unitTime_combo")
        self.unitTime_combo.addItem("")
        self.unitTime_combo.addItem("")
        self.unitTime_combo.addItem("")
        self.unitTime_combo.addItem("")
        self.unitTime_combo.addItem("")
        self.unitTime_combo.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.unitTime_combo)
        self.unitAcc_label = QtWidgets.QLabel(Dialog)
        self.unitAcc_label.setObjectName("unitAcc_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.unitAcc_label)
        self.unitAcc_combo = QtWidgets.QComboBox(Dialog)
        self.unitAcc_combo.setObjectName("unitAcc_combo")
        self.unitAcc_combo.addItem("")
        self.unitAcc_combo.addItem("")
        self.unitAcc_combo.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.unitAcc_combo)
        self.verticalLayout.addLayout(self.formLayout)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.parameters_table = QtWidgets.QTableWidget(Dialog)
        self.parameters_table.setObjectName("parameters_table")
        self.parameters_table.setColumnCount(0)
        self.parameters_table.setRowCount(0)
        self.verticalLayout.addWidget(self.parameters_table)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_6.addWidget(self.buttonBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.header_label = QtWidgets.QLabel(Dialog)
        self.header_label.setObjectName("header_label")
        self.verticalLayout_3.addWidget(self.header_label)
        self.sample_edit = QtWidgets.QPlainTextEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sample_edit.sizePolicy().hasHeightForWidth())
        self.sample_edit.setSizePolicy(sizePolicy)
        self.sample_edit.setMaximumSize(QtCore.QSize(16777215, 110))
        self.sample_edit.setObjectName("sample_edit")
        self.verticalLayout_3.addWidget(self.sample_edit)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.data_table = QtWidgets.QTableWidget(Dialog)
        self.data_table.setObjectName("data_table")
        self.data_table.setColumnCount(0)
        self.data_table.setRowCount(0)
        self.verticalLayout_3.addWidget(self.data_table)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.import_button.setText(_translate("Dialog", "Import"))
        self.columTime_label.setText(_translate("Dialog", "Column with time data"))
        self.columnAcc_label.setText(_translate("Dialog", "Column with acceleration data"))
        self.unitTime_label.setText(_translate("Dialog", "Unit of time data"))
        self.unitTime_combo.setItemText(0, _translate("Dialog", "ChipTimeUS"))
        self.unitTime_combo.setItemText(1, _translate("Dialog", "ns"))
        self.unitTime_combo.setItemText(2, _translate("Dialog", "ms"))
        self.unitTime_combo.setItemText(3, _translate("Dialog", "s"))
        self.unitTime_combo.setItemText(4, _translate("Dialog", "min"))
        self.unitTime_combo.setItemText(5, _translate("Dialog", "h"))
        self.unitAcc_label.setText(_translate("Dialog", "Unit of acceleration data"))
        self.unitAcc_combo.setItemText(0, _translate("Dialog", "g"))
        self.unitAcc_combo.setItemText(1, _translate("Dialog", "ms^2"))
        self.unitAcc_combo.setItemText(2, _translate("Dialog", "custom"))
        self.label_2.setText(_translate("Dialog", "Measured parameters with current settings:"))
        self.header_label.setText(_translate("Dialog", "Header"))
        self.label.setText(_translate("Dialog", "Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

