# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_wavimport.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1228, 336)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.import_button = QtWidgets.QPushButton(Dialog)
        self.import_button.setObjectName("import_button")
        self.horizontalLayout_4.addWidget(self.import_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.fs_label = QtWidgets.QLabel(Dialog)
        self.fs_label.setObjectName("fs_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fs_label)
        self.fs_combo = QtWidgets.QComboBox(Dialog)
        self.fs_combo.setObjectName("fs_combo")
        self.fs_combo.addItem("")
        self.fs_combo.addItem("")
        self.fs_combo.addItem("")
        self.fs_combo.addItem("")
        self.fs_combo.addItem("")
        self.fs_combo.addItem("")
        self.fs_combo.addItem("")
        self.fs_combo.addItem("")
        self.fs_combo.addItem("")
        self.fs_combo.addItem("")
        self.fs_combo.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fs_combo)
        self.columTime_label = QtWidgets.QLabel(Dialog)
        self.columTime_label.setObjectName("columTime_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.columTime_label)
        self.columnTime_combo = QtWidgets.QComboBox(Dialog)
        self.columnTime_combo.setEnabled(False)
        self.columnTime_combo.setObjectName("columnTime_combo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.columnTime_combo)
        self.columnAcc_label = QtWidgets.QLabel(Dialog)
        self.columnAcc_label.setObjectName("columnAcc_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.columnAcc_label)
        self.columnAcc_combo = QtWidgets.QComboBox(Dialog)
        self.columnAcc_combo.setEnabled(False)
        self.columnAcc_combo.setObjectName("columnAcc_combo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.columnAcc_combo)
        self.unitTime_label = QtWidgets.QLabel(Dialog)
        self.unitTime_label.setObjectName("unitTime_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.unitTime_label)
        self.unitTime_combo = QtWidgets.QComboBox(Dialog)
        self.unitTime_combo.setObjectName("unitTime_combo")
        self.unitTime_combo.addItem("")
        self.unitTime_combo.addItem("")
        self.unitTime_combo.addItem("")
        self.unitTime_combo.addItem("")
        self.unitTime_combo.addItem("")
        self.unitTime_combo.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.unitTime_combo)
        self.scaleTime_label = QtWidgets.QLabel(Dialog)
        self.scaleTime_label.setObjectName("scaleTime_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.scaleTime_label)
        self.scaleTime_edit = QtWidgets.QLineEdit(Dialog)
        self.scaleTime_edit.setEnabled(False)
        self.scaleTime_edit.setObjectName("scaleTime_edit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.scaleTime_edit)
        self.unitAcc_label = QtWidgets.QLabel(Dialog)
        self.unitAcc_label.setObjectName("unitAcc_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.unitAcc_label)
        self.unitAcc_combo = QtWidgets.QComboBox(Dialog)
        self.unitAcc_combo.setObjectName("unitAcc_combo")
        self.unitAcc_combo.addItem("")
        self.unitAcc_combo.addItem("")
        self.unitAcc_combo.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.unitAcc_combo)
        self.scaleAcc_label = QtWidgets.QLabel(Dialog)
        self.scaleAcc_label.setObjectName("scaleAcc_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.scaleAcc_label)
        self.scaleAcc_edit = QtWidgets.QLineEdit(Dialog)
        self.scaleAcc_edit.setEnabled(False)
        self.scaleAcc_edit.setObjectName("scaleAcc_edit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.scaleAcc_edit)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_6.addWidget(self.buttonBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sample_label = QtWidgets.QLabel(Dialog)
        self.sample_label.setObjectName("sample_label")
        self.verticalLayout_3.addWidget(self.sample_label)
        self.sample_edit = QtWidgets.QPlainTextEdit(Dialog)
        self.sample_edit.setObjectName("sample_edit")
        self.verticalLayout_3.addWidget(self.sample_edit)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.import_button.setText(_translate("Dialog", "Import"))
        self.fs_label.setText(_translate("Dialog", "Wav sample rate"))
        self.fs_combo.setItemText(0, _translate("Dialog", "8000"))
        self.fs_combo.setItemText(1, _translate("Dialog", "9600"))
        self.fs_combo.setItemText(2, _translate("Dialog", "11025"))
        self.fs_combo.setItemText(3, _translate("Dialog", "12000"))
        self.fs_combo.setItemText(4, _translate("Dialog", "16000"))
        self.fs_combo.setItemText(5, _translate("Dialog", "22050"))
        self.fs_combo.setItemText(6, _translate("Dialog", "24000"))
        self.fs_combo.setItemText(7, _translate("Dialog", "32000"))
        self.fs_combo.setItemText(8, _translate("Dialog", "44100"))
        self.fs_combo.setItemText(9, _translate("Dialog", "48000"))
        self.fs_combo.setItemText(10, _translate("Dialog", "88200"))
        self.columTime_label.setText(_translate("Dialog", "Column with time data"))
        self.columnAcc_label.setText(_translate("Dialog", "Column with acceleration data"))
        self.unitTime_label.setText(_translate("Dialog", "Unit of time data"))
        self.unitTime_combo.setItemText(0, _translate("Dialog", "ns"))
        self.unitTime_combo.setItemText(1, _translate("Dialog", "ms"))
        self.unitTime_combo.setItemText(2, _translate("Dialog", "s"))
        self.unitTime_combo.setItemText(3, _translate("Dialog", "min"))
        self.unitTime_combo.setItemText(4, _translate("Dialog", "h"))
        self.unitTime_combo.setItemText(5, _translate("Dialog", "custom"))
        self.scaleTime_label.setText(_translate("Dialog", "Scale time to seconds"))
        self.scaleTime_edit.setText(_translate("Dialog", "0"))
        self.unitAcc_label.setText(_translate("Dialog", "Unit of acceleration data"))
        self.unitAcc_combo.setItemText(0, _translate("Dialog", "g"))
        self.unitAcc_combo.setItemText(1, _translate("Dialog", "ms^2"))
        self.unitAcc_combo.setItemText(2, _translate("Dialog", "custom"))
        self.scaleAcc_label.setText(_translate("Dialog", "Scale acceleration to g"))
        self.scaleAcc_edit.setText(_translate("Dialog", "0"))
        self.sample_label.setText(_translate("Dialog", "Sample of imported data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

